// Generated by scripts/build-logos.js — do not edit by hand.
//
// Manufacturer logos, keyed by a normalised make name. The Figma exports are
// bitmaps inside an SVG <pattern>, so these are images rather than glyphs and
// cannot be tinted.

export const VEHICLE_LOGOS = {
  bikes: {
    'aermacchi': require('../../assets/logos/bikes/aermacchi.png'),
    'ajs': require('../../assets/logos/bikes/ajs.png'),
    'aprilla': require('../../assets/logos/bikes/aprilla.png'),
    'benelli': require('../../assets/logos/bikes/benelli.png'),
    'bsa': require('../../assets/logos/bikes/bsa.png'),
    'ducati': require('../../assets/logos/bikes/ducati.png'),
    'harley-davidson': require('../../assets/logos/bikes/harley-davidson.png'),
    'hd-aermacchi': require('../../assets/logos/bikes/hd-aermacchi.png'),
    'honda': require('../../assets/logos/bikes/honda.png'),
    'kawasaki': require('../../assets/logos/bikes/kawasaki.png'),
    'lambretta': require('../../assets/logos/bikes/lambretta.png'),
    'laverda': require('../../assets/logos/bikes/laverda.png'),
    'moto-guzzi': require('../../assets/logos/bikes/moto-guzzi.png'),
    'mv-augusta': require('../../assets/logos/bikes/mv-augusta.png'),
    'norton': require('../../assets/logos/bikes/norton.png'),
    'piaggio': require('../../assets/logos/bikes/piaggio.png'),
    'suzuki': require('../../assets/logos/bikes/suzuki.png'),
    'triumph': require('../../assets/logos/bikes/triumph.png'),
    'vespa': require('../../assets/logos/bikes/vespa.png'),
    'yamaha': require('../../assets/logos/bikes/yamaha.png'),
  },
  cars: {
    'a.d-tramontana': require('../../assets/logos/cars/a.d-tramontana.png'),
    'abarth': require('../../assets/logos/cars/abarth.png'),
    'ac': require('../../assets/logos/cars/ac.png'),
    'acura': require('../../assets/logos/cars/acura.png'),
    'adler': require('../../assets/logos/cars/adler.png'),
    'aec': require('../../assets/logos/cars/aec.png'),
    'ak': require('../../assets/logos/cars/ak.png'),
    'alfa-romeo': require('../../assets/logos/cars/alfa-romeo.png'),
    'alpina': require('../../assets/logos/cars/alpina.png'),
    'alpine': require('../../assets/logos/cars/alpine.png'),
    'alvis': require('../../assets/logos/cars/alvis.png'),
    'amc': require('../../assets/logos/cars/amc.png'),
    'ariel': require('../../assets/logos/cars/ariel.png'),
    'armstrong-siddeley': require('../../assets/logos/cars/armstrong-siddeley.png'),
    'aston-martin': require('../../assets/logos/cars/aston-martin.png'),
    'audi': require('../../assets/logos/cars/audi.png'),
    'austin': require('../../assets/logos/cars/austin.png'),
    'austin-healey': require('../../assets/logos/cars/austin-healey.png'),
    'autobianchi': require('../../assets/logos/cars/autobianchi.png'),
    'bentley': require('../../assets/logos/cars/bentley.png'),
    'bmw': require('../../assets/logos/cars/bmw.png'),
    'bristol': require('../../assets/logos/cars/bristol.png'),
    'bugatti': require('../../assets/logos/cars/bugatti.png'),
    'buick': require('../../assets/logos/cars/buick.png'),
    'caddilac': require('../../assets/logos/cars/caddilac.png'),
    'chevrolet': require('../../assets/logos/cars/chevrolet.png'),
    'chrysler': require('../../assets/logos/cars/chrysler.png'),
    'citroen': require('../../assets/logos/cars/citroen.png'),
    'cord': require('../../assets/logos/cars/cord.png'),
    'daimler': require('../../assets/logos/cars/daimler.png'),
    'delahaye': require('../../assets/logos/cars/delahaye.png'),
    'dellow': require('../../assets/logos/cars/dellow.png'),
    'desoto': require('../../assets/logos/cars/desoto.png'),
    'dodge': require('../../assets/logos/cars/dodge.png'),
    'duesenberg': require('../../assets/logos/cars/duesenberg.png'),
    'ferarri': require('../../assets/logos/cars/ferarri.png'),
    'fiat': require('../../assets/logos/cars/fiat.png'),
    'ford': require('../../assets/logos/cars/ford.png'),
    'gm': require('../../assets/logos/cars/gm.png'),
    'hillman': require('../../assets/logos/cars/hillman.png'),
    'hudson': require('../../assets/logos/cars/hudson.png'),
    'jaguar': require('../../assets/logos/cars/jaguar.png'),
    'jensen': require('../../assets/logos/cars/jensen.png'),
    'jowett': require('../../assets/logos/cars/jowett.png'),
    'lagonda': require('../../assets/logos/cars/lagonda.png'),
    'lamborghini': require('../../assets/logos/cars/lamborghini.png'),
    'lancia': require('../../assets/logos/cars/lancia.png'),
    'land-rover': require('../../assets/logos/cars/land-rover.png'),
    'lincoln': require('../../assets/logos/cars/lincoln.png'),
    'lotus': require('../../assets/logos/cars/lotus.png'),
    'maserati': require('../../assets/logos/cars/maserati.png'),
    'mazda': require('../../assets/logos/cars/mazda.png'),
    'mercedes-benz': require('../../assets/logos/cars/mercedes-benz.png'),
    'mercury': require('../../assets/logos/cars/mercury.png'),
    'mg': require('../../assets/logos/cars/mg.png'),
    'mini': require('../../assets/logos/cars/mini.png'),
    'morris': require('../../assets/logos/cars/morris.png'),
    'oldsmobile': require('../../assets/logos/cars/oldsmobile.png'),
    'opel': require('../../assets/logos/cars/opel.png'),
    'packard': require('../../assets/logos/cars/packard.png'),
    'plymouth': require('../../assets/logos/cars/plymouth.png'),
    'pontiac': require('../../assets/logos/cars/pontiac.png'),
    'porsche': require('../../assets/logos/cars/porsche.png'),
    'renault': require('../../assets/logos/cars/renault.png'),
    'riley': require('../../assets/logos/cars/riley.png'),
    'rolls-royce': require('../../assets/logos/cars/rolls-royce.png'),
    'rosengart': require('../../assets/logos/cars/rosengart.png'),
    'rover': require('../../assets/logos/cars/rover.png'),
    'studebaker': require('../../assets/logos/cars/studebaker.png'),
    'sunbeam': require('../../assets/logos/cars/sunbeam.png'),
    'triumph': require('../../assets/logos/cars/triumph.png'),
    'vauxhall': require('../../assets/logos/cars/vauxhall.png'),
  },
  commercial: {
    'aec': require('../../assets/logos/commercial/aec.png'),
    'bedford': require('../../assets/logos/commercial/bedford.png'),
    'citroen': require('../../assets/logos/commercial/citroen.png'),
    'fiat': require('../../assets/logos/commercial/fiat.png'),
    'ford': require('../../assets/logos/commercial/ford.png'),
    'leyland': require('../../assets/logos/commercial/leyland.png'),
    'mercedes-benz': require('../../assets/logos/commercial/mercedes-benz.png'),
    'mitsubishi': require('../../assets/logos/commercial/mitsubishi.png'),
    'morris': require('../../assets/logos/commercial/morris.png'),
    'peugeot': require('../../assets/logos/commercial/peugeot.png'),
    'volvo': require('../../assets/logos/commercial/volvo.png'),
    'vw': require('../../assets/logos/commercial/vw.png'),
  },
};

/** Normalise a make name the way the generator slugs filenames. */
export function logoKey(make) {
  return String(make).trim().toLowerCase().replace(/[\s_]+/g, '-');
}

/**
 * Look a make up across every category. Returns null when no logo exists, so
 * callers can fall back rather than render a broken image.
 */
export function vehicleLogo(make, category) {
  const key = logoKey(make);
  if (category) return VEHICLE_LOGOS[category]?.[key] ?? null;
  for (const group of Object.values(VEHICLE_LOGOS)) {
    if (group[key]) return group[key];
  }
  return null;
}
