/**
 * Turns the SVGs exported from Figma (Icons/Icon/Regular/*.svg) into a plain
 * glyph map the app can render through <AppIcon>.
 *
 * Run after adding or replacing any icon:
 *   node scripts/build-icons.js
 *
 * Extracting the path data (rather than importing the SVG files directly) keeps
 * the fill controllable from code — the exports hardcode brand green, but the
 * same glyph is needed in other colours.
 */
const fs = require('fs');
const path = require('path');

const SOURCE_DIR = path.join(__dirname, '..', 'Icons');
const OUTPUT = path.join(__dirname, '..', 'components', 'icons', 'glyphs.js');

function walk(dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) return walk(full);
    return entry.name.endsWith('.svg') ? [full] : [];
  });
}

function parse(file) {
  const svg = fs.readFileSync(file, 'utf8');
  const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1];
  // Only the drawing paths; the exports wrap them in a fill="none" root.
  //
  // `fill-rule` has to travel with the path: line-art icons are exported as a
  // single evenodd path whose inner contours knock out the outer one. Dropping
  // the rule falls back to nonzero, which fills those holes in and turns the
  // outline into a solid blob.
  const paths = [...svg.matchAll(/<path\b[^>]*>/g)]
    .map((m) => {
      const tag = m[0];
      const d = tag.match(/\sd="([^"]+)"/)?.[1];
      if (!d) return null;
      const rule = tag.match(/fill-rule="([^"]+)"/)?.[1];
      return rule === 'evenodd' ? { d, rule } : { d };
    })
    .filter(Boolean);
  if (!viewBox || paths.length === 0) return null;
  return { viewBox, paths };
}

/**
 * Figma export names are inconsistent — "Calendar", "driver side",
 * "logo-full-insurance-cnc 1". Normalise to kebab-case and drop the trailing
 * counter Figma adds when re-exporting an identical glyph.
 */
function slugify(basename) {
  return basename
    .replace(/[-\s]\d+$/, '')
    .trim()
    .toLowerCase()
    .replace(/\s+/g, '-');
}

const seen = new Map();
const skipped = [];

for (const file of walk(SOURCE_DIR).sort()) {
  const name = slugify(path.basename(file, '.svg'));
  const parsed = parse(file);
  if (!parsed) {
    skipped.push(`${path.relative(SOURCE_DIR, file)} (no path/viewBox)`);
    continue;
  }
  if (seen.has(name)) continue;
  seen.set(name, parsed);
}

const entries = [...seen.entries()]
  .map(
    ([name, { viewBox, paths }]) =>
      `  '${name}': {\n    viewBox: '${viewBox}',\n    paths: [\n${paths
        .map(({ d, rule }) =>
          rule ? `      { d: '${d}', rule: '${rule}' },` : `      { d: '${d}' },`
        )
        .join('\n')}\n    ],\n  },`
  )
  .join('\n');

const output = `// GENERATED by scripts/build-icons.js — do not edit by hand.
// Source: Icons/Icon/Regular/*.svg (FontAwesome Pro Regular, exported from Figma).

export const GLYPHS = {
${entries}
};

export const GLYPH_NAMES = Object.keys(GLYPHS);
`;

fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });
fs.writeFileSync(OUTPUT, output);

console.log(`Wrote ${seen.size} glyphs to ${path.relative(process.cwd(), OUTPUT)}:`);
console.log('  ' + [...seen.keys()].join(', '));
if (skipped.length) console.log('Skipped:\n  ' + skipped.join('\n  '));
