/**
 * Extracts the vehicle manufacturer logos from the Figma exports.
 *
 * Unlike the icon glyphs, these are bitmaps embedded inside an SVG <pattern>,
 * so they cannot be tinted paths — each becomes a real PNG asset plus an entry
 * in components/logos/vehicleLogos.js keyed by a normalised make name.
 *
 * Usage: node scripts/build-logos.js
 */

const fs = require('fs');
const path = require('path');

const SOURCE_DIR = path.join(__dirname, '..', 'Icons', 'Icon', 'Vehicle logo', 'Logos');
const ASSET_DIR = path.join(__dirname, '..', 'assets', 'logos');
const OUT_FILE = path.join(__dirname, '..', 'components', 'logos', 'vehicleLogos.js');

function walk(dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) return walk(full);
    return entry.name.toLowerCase().endsWith('.svg') ? [full] : [];
  });
}

/** "Alfa-Romeo" / "Rolls Royce" / "Rover-1" -> "alfa-romeo" / "rolls-royce" / "rover" */
function slugify(basename) {
  return basename
    .replace(/[-\s]\d+$/, '')
    .trim()
    .toLowerCase()
    .replace(/[\s_]+/g, '-');
}

function extract(file) {
  const svg = fs.readFileSync(file, 'utf8');
  const match = svg.match(/xlink:href="data:image\/(png|jpe?g);base64,([^"]+)"/);
  if (!match) return null;
  return { ext: match[1] === 'jpg' ? 'jpeg' : match[1], data: Buffer.from(match[2], 'base64') };
}

fs.mkdirSync(ASSET_DIR, { recursive: true });
fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });

const entries = new Map();
const skipped = [];

for (const file of walk(SOURCE_DIR).sort()) {
  const category = path.basename(path.dirname(file)).toLowerCase();
  const slug = slugify(path.basename(file, '.svg'));
  const key = `${category}/${slug}`;

  if (entries.has(key)) continue;

  const image = extract(file);
  if (!image) {
    skipped.push(path.relative(SOURCE_DIR, file));
    continue;
  }

  const dir = path.join(ASSET_DIR, category);
  fs.mkdirSync(dir, { recursive: true });
  const filename = `${slug}.png`;
  fs.writeFileSync(path.join(dir, filename), image.data);
  entries.set(key, { category, slug, filename });
}

const byCategory = {};
for (const { category, slug, filename } of entries.values()) {
  (byCategory[category] ??= []).push({ slug, filename });
}

const lines = [];
lines.push('// Generated by scripts/build-logos.js — do not edit by hand.');
lines.push('//');
lines.push('// Manufacturer logos, keyed by a normalised make name. The Figma exports are');
lines.push('// bitmaps inside an SVG <pattern>, so these are images rather than glyphs and');
lines.push('// cannot be tinted.');
lines.push('');
lines.push('export const VEHICLE_LOGOS = {');
for (const category of Object.keys(byCategory).sort()) {
  lines.push(`  ${category}: {`);
  for (const { slug, filename } of byCategory[category].sort((a, b) => a.slug.localeCompare(b.slug))) {
    lines.push(`    '${slug}': require('../../assets/logos/${category}/${filename}'),`);
  }
  lines.push('  },');
}
lines.push('};');
lines.push('');
lines.push('/** Normalise a make name the way the generator slugs filenames. */');
lines.push('export function logoKey(make) {');
lines.push("  return String(make).trim().toLowerCase().replace(/[\\s_]+/g, '-');");
lines.push('}');
lines.push('');
lines.push('/**');
lines.push(' * Look a make up across every category. Returns null when no logo exists, so');
lines.push(' * callers can fall back rather than render a broken image.');
lines.push(' */');
lines.push('export function vehicleLogo(make, category) {');
lines.push('  const key = logoKey(make);');
lines.push('  if (category) return VEHICLE_LOGOS[category]?.[key] ?? null;');
lines.push('  for (const group of Object.values(VEHICLE_LOGOS)) {');
lines.push('    if (group[key]) return group[key];');
lines.push('  }');
lines.push('  return null;');
lines.push('}');
lines.push('');

fs.writeFileSync(OUT_FILE, lines.join('\n'));

const counts = Object.entries(byCategory)
  .map(([c, list]) => `${c}: ${list.length}`)
  .join(', ');
console.log(`Wrote ${entries.size} logos (${counts})`);
console.log(`  assets -> ${path.relative(process.cwd(), ASSET_DIR)}`);
console.log(`  map    -> ${path.relative(process.cwd(), OUT_FILE)}`);
if (skipped.length) console.log(`Skipped (no embedded image):\n  ${skipped.join('\n  ')}`);
